app = "npchat-rocketkv"

[build]
dockerfile = "fly.Dockerfile"

[[services]]
  internal_port = 8100
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"
